print("Calculator V1.0")
print("Created by WollyDev24")
print("Enter first number")
input1 = input(">> ")
print("Enter second number")
input2 = input(">> ")
print("Enter operation (+, -, *, /)")
operation = input(">> ")
print("Hello World")