# UselessPyProgress - A simple Progress Bar that does nothing useful
import time

print("Porgress V1.0")
print("Created by WollyDev24")
print("Enter y to start Progress Bar")
input1 = input(">> ")
print("[█                    ] 0%")
time.sleep(0.5)
print("[██                   ] 0%")
time.sleep(0.5)
print("[████                 ] 10%")
time.sleep(0.5)
print("[█████                ] 20%")
time.sleep(0.5)
print("[███████              ] 30%")
time.sleep(0.5)
print("[████████             ] 40%")
time.sleep(0.5)
print("[█████████            ] 50%")
time.sleep(0.5)
print("[███████████          ] 60%")
time.sleep(0.5)
print("[████████████         ] 70%")
time.sleep(0.5)
print("[█████████████        ] 80%")
time.sleep(0.5)
print("[███████████████      ] 90%")
time.sleep(0.5)
print("[███████████████████  ] 99%")  
time.sleep(0.5)
print("Error: Progress Bar Failed to Load")
